export const phraseBank = [
    "AI-powered mentioned on booth",
    "Booth raffle prize is something no one cares about",
    "Booth is food establishment themed",
    "AI Powered SOC",
    "Legacy company inserts AI into something that doesn't need it",
    "Get randomly scanned by a booth",
    "Someone tries to set up a meeting with you after BlackHat",
    "Has a demo screen with no demo running",
    'Someone interrupts a conversation you are having with an "influencer"',
    "Drinks scheduled before noon",
    "Someone mentions the Hugging Face breach",
    'Something claims to be "the only security tool you will ever need"',
    "Zero trust is mentioned",
    "C-Suite Ready Reporting",
    "Continuous compliance is mentioned",
    "FUD (fear, uncertainty, and doubt) is used in the pitch",
    "A CISO's guide is at a booth",
    "Booth staff in matching polos",
    '"Recently acquired" is mentioned on a booth',
    "Swag collector comes to the booth",
    '"I was a hacker back in the day actually"',
    "Someone randomly mentions a high level connection they have to the company",
    "A company recently came out of stealth",
    "Random ARR or funding round is plastered on the booth or peripheral spaces",
    "Someone tries to bribe you with swag",
    "Something is called Next-Gen (it's really just powered by frontier models)",
    "Autonomous something is mentioned",
    "Someone mentions that this is unprecedented times",
    "Something claims to be frictionless security",
    "Logo soup to prove market validity",
    "Random celebrity is used to drive traffic to a talk or company event",
    "There's a lockpicking station",
    '"Try it for yourself" demo station',
    "Something claims to protect against nation states",
    "There's a claim about false positives",
    "Cloud native",
    "Someone treats you like a buyer or someone with purchasing power when you don't have any",
    "We bring you greater visibility",
    "Resilience is mentioned",
    "We compliment your security, not replace it"
]